### ISSUE TITLE
偶尔会登录失败，服务器抛出异常

### ISSUE THREAD

**Issue by seanjsong** [zhaoyao91/meteor-short-oauth-state#3]
服务器log中显示：

```
{"line":"218","file":"oauth.js","message":"Error in OAuth Server while storing pending login result.\nError: Match error: Expected string, got undefined\n    at exports.check (packages/check.js:57:15)\n    at Object.OAuth._storePendingCredential (packages/oauth.js:560:3)\n    at middleware (packages/oauth.js:214:15)\n    at packages/oauth.js:176:5","time":{"$date":1492897154713},"level":"warn"}
{"line":"234","file":"oauth.js","message":"Error generating end of login response\nError: Unrecognized login style: undefined\n    at Object.OAuth._loginStyleFromQuery (packages/oauth.js:124:11)\n    at middleware (packages/oauth.js:230:27)\n    at packages/oauth.js:176:5","time":{"$date":1492897154716},"level":"warn"}
```

原因如下。在accounts-wechat-mp和accounts-wechat包里都是这样登录的：

```
    var state = OAuth._stateParam(loginStyle, credentialToken, options.redirectUrl);

    var loginUrl =
        'https://open.weixin.qq.com/connect/qrconnect' +
        '?appid=' + config.appId +
        '&redirect_uri=' + OAuth._redirectUri(serviceName, config, null, {replaceLocalhost: true}) +
        '&response_type=code' +
        '&scope=' + scope +
        '&state=' + state +
        '#wechat_redirect';

    OAuth.launchLogin({
        loginService: serviceName,
        loginStyle: loginStyle,
        loginUrl: loginUrl,
        credentialRequestCompleteCallback: credentialRequestCompleteCallback,
        credentialToken: credentialToken
    });
```

OAuth._stateParam()里面有一个Meteor.call('zhaoyao91:short-oauth-state.setState')，但OAuth._stateParam()没等它返回就自己先返回了，很快就执行到了OAuth.launchLogin()，其中会重定向页面，在重定向之前Meteor.call如果还没来得及发出去，会因为连接断开而发不出去了。所以到了服务器查询state的OAuth._stateFromQuery()调用时，查找state发现没有，于是返回缺省值{}。于是抛出上述异常。

要保证登录的可靠性，需要传一个callback给OAuth._stateParam()，在callback中才调OAuth.launchLogin()。这个改动会触及三个package，并且不仅覆盖了Meteor原先的OAuth._stateParam()，甚至连参数列表也要变得不一样了。

**Comment by zhaoyao91** [comment]
你有什么好的建议吗？

**Comment by seanjsong** [comment]
我建议就那么改吧 8-)
OAuth._stateParam = function (loginStyle, credentialToken, redirectUrl, callback)

**Comment by zhaoyao91** [comment]
done，请更新short-oauth-state和accounts-wechat-mp到最新版本试一下吧

**Comment by seanjsong** [comment]
效率好高呀〜刚试了accounts-wechat-mp，没问题。请把accounts-wechat包也更新一下吧，多谢〜〜〜

**Comment by zhaoyao91** [comment]
好了，试一下？

**Comment by seanjsong** [comment]
欧了。多谢〜
